baseURL: 'https://atul.nepal.com.np/'
languageCode: en-us
title: Rane ko Ban
theme: RaneTheme


menu:
  main:
    - identifier: categories
      name: Categories
      weight: 1
      url: /categories/
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: cla
      name: Cla
      url: /cla/
